name: ventemoi
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  google_fonts:
  intl:

  get:
  get_storage:
  file_picker:
  auto_size_text:
  url_launcher:

  firebase_auth:
  cloud_firestore:
  firebase_storage:

  google_places_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/logo-placeholder.png
    - images/background.png
    - images/background-opacity.png

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: fonts/SpaceGrotesk.ttf
    - family: LexendDeca
      fonts:
        - asset: fonts/LexendDeca.ttf
    - family: Cano
      fonts:
        - asset: fonts/Cano.otf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
